### ISSUE TITLE
Attribute "updated" has not found

### ISSUE THREAD

**Issue by dlpigpen** [jcoynel/app-store-reviews#2]
Thanks for your library. it's useful for me and everyone else.

So, I have the question for you. We would like to know reviews' updated date. We did not found the attribute in your body jSon. How We can show it in review object ?

Thanks,

**Comment by jcoynel** [comment]
Hi dlpigpen,

I've updated app-store-reviews to use the xml feed so you can now get access to the updated date.

Thanks
