### ISSUE TITLE
It seems that the page number cannot bigger than 10. Is there a solution?

### ISSUE THREAD

**Issue by zhzehong** [jcoynel/app-store-reviews#4]

**Comment by jcoynel** [comment]
Hi @zhzehong,
You're right, the Apple feed used by app-store-reviews only supports 10 pages. There might be other tools relying on a different data source able to fetch all the reviews. I couldn't find any at the time I started this project but I've not looked for it recently so they may exist.
Please let me know if you find anything, we might be able to update app-store-reviews.
Thanks
